VERSION 0.8

# Perform a Debian UsrMerge on a package.
USR_MERGE:
  FUNCTION
  ARG src
  ARG dst
  RUN src=$(realpath "${src}") \
    && dst=$(realpath "${dst}") \
    && workdir=$(mktemp -d) \
    && cd "${workdir}" \
    && dpkg-deb -x "${src}" . \
    && dpkg-deb --control "${src}" \
    && mkdir -p usr \
    && mv $(find . -maxdepth 1 -name bin -or -name sbin -or -name lib -or -name lib32 -or -name lib64 -or -name libo32 -or -name libx32) usr/ \
    && dpkg-deb --build . "${dst}"

# Mark a package with a virtual alias.
ALIAS:
  FUNCTION
  ARG src
  ARG dst
  ARG provides
  RUN src=$(realpath "${src}") \
    && dst=$(realpath "${dst}") \
    && workdir=$(mktemp -d) \
    && cd "${workdir}" \
    && dpkg-deb -x "${src}" . \
    && dpkg-deb --control "${src}" \
    && echo "Provides: ${provides}" >> DEBIAN/control \
    && dpkg-deb --build . "${dst}"

bookworm-base:
  FROM debian:bookworm
  ENV DO_NOT_TRACK=1
  RUN apt update
  RUN apt install -y build-essential \
    crossbuild-essential-arm64 g++-riscv64-linux-gnu gcc-riscv64-linux-gnu \
    bc bison flex libssl-dev swig python3 python3-dev python3-setuptools \
    libncurses-dev libssl-dev libelf-dev curl debhelper fakeroot git \
    linux-source
  RUN mkdir -p /workspace \
    && tar -xf /usr/src/linux-source-6.1.tar.xz -C /workspace
  WORKDIR /workspace/linux-source-6.1
  ENV KERNELVERSION=$(make kernelversion)

trixie-base:
  FROM debian:trixie
  ENV DO_NOT_TRACK=1
  RUN apt update
  RUN apt install -y build-essential \
    crossbuild-essential-arm64 g++-riscv64-linux-gnu gcc-riscv64-linux-gnu \
    bc bison flex libssl-dev swig python3 python3-dev python3-setuptools \
    libncurses-dev libssl-dev libelf-dev curl debhelper fakeroot git \
    linux-source
  RUN mkdir -p /workspace \
    && tar -xf /usr/src/linux-source-6.10.tar.xz -C /workspace
  WORKDIR /workspace/linux-source-6.10
  ENV KERNELVERSION=$(make kernelversion)

bootloader-base:
  FROM +bookworm-base
  WORKDIR /workspace
  GIT CLONE --branch=24.08 https://github.com/coreboot/coreboot.git coreboot
  GIT CLONE --branch=v2024.01 https://github.com/u-boot/u-boot.git u-boot