VERSION 0.8

# Perform a Debian UsrMerge on a package.
USR_MERGE:
  FUNCTION
  ARG package
  RUN package=$(realpath "${package}") \
    && workdir=$(mktemp -d) \
    && cd "${workdir}" \
    && dpkg-deb -x "${package}" . \
    && dpkg-deb --control "${package}" \
    && mkdir -p usr \
    && rsync -avh $(find . -maxdepth 1 -name bin -or -name sbin -or -name lib -or -name lib32 -or -name lib64 -or -name libo32 -or -name libx32) usr/ \
    && rm -rf bin sbin lib lib32 lib64 libo32 libx32 \
    && dpkg-deb --build . "${package}"

# Create a Debian meta package (eg. an empty package that depends on another package).
META_PACKAGE:
  FUNCTION
  ARG name
  ARG version
  ARG depends
  ARG arch
  RUN outputdir=$(pwd) \
    && workdir=$(mktemp -d) \
    && cd "${workdir}" \
    && mkdir -p DEBIAN \
    && echo "Package: ${name}" > DEBIAN/control \
    && echo "Version: ${version}" >> DEBIAN/control \
    && echo "Architecture: ${arch}" >> DEBIAN/control \
    && echo "Maintainer: Damian Peckett <damian@pecke.tt>" >> DEBIAN/control \
    && echo "Description: Linux kernel meta package" >> DEBIAN/control \
    && echo "Depends: ${depends}" >> DEBIAN/control \
    && dpkg-deb --build . "${outputdir}/${name}_${version}_${arch}.deb"

# Setup symlinks for the kernel (eg. vmlinuz and dtb).
# Only one kernel version can be installed at a time in an immutos image.
KERNEL_SYMLINKS:
  FUNCTION
  ARG package
  RUN package=$(realpath "${package}") \
    && version=$(dpkg-deb --info "${package}" | grep Package | awk '{print $2}') \
    && workdir=$(mktemp -d) \
    && cd "${workdir}" \
    && dpkg-deb -x "${package}" . \
    && dpkg-deb --control "${package}" \
    && if [ -d "usr/lib/${version}" ] && [ "$(ls -A usr/lib/${version})" ]; then \
         ln -s "../usr/lib/${version}" boot/dtb; \
       fi \
    && ln -s "boot/vmlinuz-$(echo $version | sed 's/^linux-image-//')" vmlinuz \
    && dpkg-deb --build . "${package}"

bookworm-base:
  FROM debian:bookworm
  RUN apt update
  RUN apt install -y build-essential \
    crossbuild-essential-arm64 g++-riscv64-linux-gnu gcc-riscv64-linux-gnu \
    bc bison flex libssl-dev swig python3 python3-dev python3-setuptools \
    libgnutls28-dev libncurses-dev libssl-dev libelf-dev curl debhelper fakeroot \
    git rsync uuid-dev

trixie-base:
  FROM debian:trixie
  RUN apt update
  RUN apt install -y build-essential \
    crossbuild-essential-arm64 g++-riscv64-linux-gnu gcc-riscv64-linux-gnu \
    bc bison flex libssl-dev swig python3 python3-dev python3-setuptools \
    libgnutls28-dev libncurses-dev libssl-dev libelf-dev curl debhelper fakeroot \
    git rsync uuid-dev