VERSION 0.8
FROM debian:bookworm
WORKDIR /workspace
ENV DO_NOT_TRACK=1

all:
  COPY +bootloader/u-boot.bin ./dist/u-boot-qemu-arm64.bin
  COPY +linux/ ./dist/
  SAVE ARTIFACT ./dist/* AS LOCAL dist/ 

linux:
  COPY +linux-bookworm/ ./
  COPY +linux-trixie/ ./
  SAVE ARTIFACT *.deb AS LOCAL ./dist/

linux-bookworm:
  FROM ../util+bookworm-base
  ENV ARCH=arm64
  ENV CROSS_COMPILE=aarch64-linux-gnu-
  COPY linux/config-6.1 .config
  RUN make oldconfig
  RUN make -j $(nproc) LOCALVERSION=-immutos-qemu bindeb-pkg
  SAVE ARTIFACT /workspace/linux-image-${KERNELVERSION}-immutos-qemu_${KERNELVERSION}-immutos-qemu-1_arm64.deb AS LOCAL ./dist/

linux-trixie:
  FROM ../util+trixie-base
  ENV ARCH=arm64
  ENV CROSS_COMPILE=aarch64-linux-gnu-
  COPY linux/config-6.10 .config
  RUN make oldconfig
  RUN make -j $(nproc) LOCALVERSION=-immutos-qemu bindeb-pkg
  WORKDIR /workspace
  RUN mv linux-image-${KERNELVERSION}-immutos-qemu_${KERNELVERSION}-1_arm64.deb original.deb
  DO ../util+USR_MERGE --src=original.deb --dst=usrmerged.deb
  DO ../util+ALIAS --src=usrmerged.deb --dst=linux-image-${KERNELVERSION}-immutos-qemu_${KERNELVERSION}-1_arm64.deb --provides=linux-image-immutos-qemu
  SAVE ARTIFACT linux-image-${KERNELVERSION}-immutos-qemu_${KERNELVERSION}-1_arm64.deb AS LOCAL ./dist/

bootloader:
  FROM ../util+bootloader-base
  WORKDIR /workspace/u-boot
  COPY u-boot/patches/ ./patches/
  RUN for p in ./patches/*.diff; do patch -p1 < $p; done && rm -rf ./patches
  COPY u-boot/config .config
  ENV CROSS_COMPILE=aarch64-linux-gnu-
  RUN make oldconfig
  RUN make -j$(nproc)
  SAVE ARTIFACT u-boot.bin AS LOCAL dist/u-boot-qemu-arm64.bin