VERSION 0.8
FROM debian:bookworm
WORKDIR /workspace

linux-bookworm:
  FROM ../util+bookworm-base
  # Cache busting
  COPY (+source-version/version.txt --DEBIAN_RELEASE=bookworm) ./debian-version.txt
  RUN apt install -y linux-source
  RUN mkdir -p /workspace \
    && tar -xf /usr/src/linux-source-6.1.tar.xz -C /workspace
  WORKDIR /workspace/linux-source-6.1
  ENV KERNELVERSION=$(make kernelversion)
  COPY ./patches-6.1 ./patches/
  RUN for p in ./patches/*.patch; do patch -p1 < $p; done && rm -rf ./patches
  RUN rm arch/x86/configs/x86_64_defconfig
  COPY ./configs-6.1/arch/amd64_defconfig ./arch/x86/configs/defconfig
  COPY ./configs-6.1/arch/arm64_defconfig ./arch/arm64/configs/defconfig
  COPY ./configs-6.1/arch/riscv64_defconfig ./arch/riscv/configs/defconfig
  COPY ./configs-6.1/*.config ./kernel/configs/

linux-trixie:
  FROM ../util+trixie-base
  # Cache busting
  COPY (+source-version/version.txt --DEBIAN_RELEASE=trixie) ./debian-version.txt
  RUN apt install -y linux-source
  RUN mkdir -p /workspace \
    && tar -xf /usr/src/linux-source-6.11.tar.xz -C /workspace
  WORKDIR /workspace/linux-source-6.11
  ENV KERNELVERSION=$(make kernelversion)
  COPY ./patches-6.11 ./patches/
  RUN for p in ./patches/*.patch; do patch -p1 < $p; done && rm -rf ./patches
  RUN rm arch/x86/configs/x86_64_defconfig
  COPY ./configs-6.11/arch/amd64_defconfig ./arch/x86/configs/defconfig
  COPY ./configs-6.11/arch/arm64_defconfig ./arch/arm64/configs/defconfig
  COPY ./configs-6.11/arch/riscv64_defconfig ./arch/riscv/configs/defconfig
  COPY ./configs-6.11/*.config ./kernel/configs/

source-version:
  LOCALLY
  ARG DEBIAN_RELEASE
  ARG OUTPUT_DIR=$(mktemp -d)
  RUN --no-cache curl -fs "https://packages.debian.org/${DEBIAN_RELEASE}/linux-source" | grep -oP 'Package: linux-source \(\K[0-9.-]+' > "${OUTPUT_DIR}/version.txt"
  SAVE ARTIFACT "${OUTPUT_DIR}/version.txt"
