VERSION 0.8
FROM debian:bookworm
WORKDIR /workspace

linux-bookworm:
  FROM debian:bookworm
  RUN apt update
  RUN apt install -y build-essential \
    crossbuild-essential-arm64 g++-riscv64-linux-gnu gcc-riscv64-linux-gnu \
    bc bison flex libssl-dev swig python3 python3-dev python3-setuptools \
    libncurses-dev libssl-dev libelf-dev curl debhelper fakeroot git rsync \
    linux-source
  RUN mkdir -p /workspace \
    && tar -xf /usr/src/linux-source-6.1.tar.xz -C /workspace
  WORKDIR /workspace/linux-source-6.1
  ENV KERNELVERSION=$(make kernelversion)

linux-trixie:
  FROM debian:trixie
  RUN apt update
  RUN apt install -y build-essential \
    crossbuild-essential-arm64 g++-riscv64-linux-gnu gcc-riscv64-linux-gnu \
    bc bison flex libssl-dev swig python3 python3-dev python3-setuptools \
    libncurses-dev libssl-dev libelf-dev curl debhelper fakeroot git rsync \
    linux-source
  RUN mkdir -p /workspace \
    && tar -xf /usr/src/linux-source-6.11.tar.xz -C /workspace
  WORKDIR /workspace/linux-source-6.11
  ENV KERNELVERSION=$(make kernelversion)
  COPY ./patches-6.11 ./patches/
  RUN for p in ./patches/*.patch; do patch -p1 < $p; done && rm -rf ./patches
  RUN rm arch/x86/configs/x86_64_defconfig
  COPY ./configs-6.11/arch/amd64_defconfig ./arch/x86/configs/defconfig
  COPY ./configs-6.11/arch/arm64_defconfig ./arch/arm64/configs/defconfig
  COPY ./configs-6.11/arch/riscv64_defconfig ./arch/riscv/configs/defconfig
  COPY ./configs-6.11/*.config ./kernel/configs/