VERSION 0.8
FROM debian:bookworm
WORKDIR /workspace

linux-bookworm:
  FROM debian:bookworm
  RUN apt update
  RUN apt install -y build-essential \
    crossbuild-essential-arm64 g++-riscv64-linux-gnu gcc-riscv64-linux-gnu \
    bc bison flex libssl-dev swig python3 python3-dev python3-setuptools \
    libncurses-dev libssl-dev libelf-dev curl debhelper fakeroot git rsync \
    linux-source
  RUN mkdir -p /workspace \
    && tar -xf /usr/src/linux-source-6.1.tar.xz -C /workspace
  WORKDIR /workspace/linux-source-6.1
  ENV KERNELVERSION=$(make kernelversion)

linux-trixie:
  FROM debian:trixie
  RUN apt update
  RUN apt install -y build-essential \
    crossbuild-essential-arm64 g++-riscv64-linux-gnu gcc-riscv64-linux-gnu \
    bc bison flex libssl-dev swig python3 python3-dev python3-setuptools \
    libncurses-dev libssl-dev libelf-dev curl debhelper fakeroot git rsync \
    linux-source
  RUN mkdir -p /workspace \
    && tar -xf /usr/src/linux-source-6.11.tar.xz -C /workspace
  WORKDIR /workspace/linux-source-6.11
  ENV KERNELVERSION=$(make kernelversion)
  COPY linux/patches-6.11 ./patches/
  RUN for p in ./patches/*.patch; do git apply $p; done && rm -rf ./patches

bootloader:
  FROM +linux-bookworm
  WORKDIR /workspace
  GIT CLONE --branch=24.08 https://github.com/coreboot/coreboot.git coreboot
  GIT CLONE --branch=v1.5.1 https://github.com/riscv-software-src/opensbi.git opensbi
  GIT CLONE --branch=v2024.07 https://github.com/u-boot/u-boot.git u-boot